/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package numberguesslab;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author mbrester1
 */
public class MainWindow extends javax.swing.JFrame {
    private NumberGuessService ngs;
    
    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        startNewGame();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGuess = new javax.swing.JButton();
        btnQuit = new javax.swing.JButton();
        txtNumberGuess = new javax.swing.JTextField();
        lblLowEndNumber = new javax.swing.JLabel();
        lblHighEndNumber = new javax.swing.JLabel();
        lblTo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnGuess.setText("Guess");
        btnGuess.addActionListener(new NumberGuessActionListener(this));
        btnGuess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuessActionPerformed(evt);
            }
        });

        btnQuit.setText("Quit");
        btnQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitActionPerformed(evt);
            }
        });

        lblLowEndNumber.setText("jLabel1");

        lblHighEndNumber.setText("jLabel2");

        lblTo.setText("And");

        jLabel1.setText("Guess A Number Between");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnQuit)
                        .addGap(59, 59, 59)
                        .addComponent(btnGuess))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(lblTo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblHighEndNumber)))
                .addGap(0, 106, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLowEndNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(137, 137, 137))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(txtNumberGuess, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(144, 144, 144)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLowEndNumber)
                    .addComponent(lblHighEndNumber)
                    .addComponent(lblTo))
                .addGap(31, 31, 31)
                .addComponent(txtNumberGuess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnQuit)
                    .addComponent(btnGuess))
                .addGap(144, 144, 144))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuessActionPerformed
 
    }//GEN-LAST:event_btnGuessActionPerformed

    private void btnQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitActionPerformed
      System.exit(1);
    }//GEN-LAST:event_btnQuitActionPerformed

    /**
     * @param args the command line arguments
     */
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuess;
    private javax.swing.JButton btnQuit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblHighEndNumber;
    private javax.swing.JLabel lblLowEndNumber;
    private javax.swing.JLabel lblTo;
    private javax.swing.JTextField txtNumberGuess;
    // End of variables declaration//GEN-END:variables

    private void startNewGame(){
        try{
        this.ngs = new NumberGuessService();
        ngs.setLowNumber(Integer.valueOf(JOptionPane.showInputDialog("Enter a Low End Number")));
        Integer temp = ngs.getLowNumber();
        lblLowEndNumber.setText(temp.toString());
        ngs.setHighNumber(Integer.valueOf(JOptionPane.showInputDialog("Enter a High End Number")));
        temp = ngs.getHighNumber();
        lblHighEndNumber.setText(temp.toString());
        }catch(IllegalArgumentException e){
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
            System.exit(1);
        }finally{
            ngs.setRandomNumber();
        }
    }

    public NumberGuessService getNgs() {
        return ngs;
    }

    public void setNgs(NumberGuessService ngs) {
        this.ngs = ngs;
    }

    public JButton getBtnGuess() {
        return btnGuess;
    }

    public void setBtnGuess(JButton btnGuess) {
        this.btnGuess = btnGuess;
    }

    public JButton getBtnQuit() {
        return btnQuit;
    }

    public void setBtnQuit(JButton btnQuit) {
        this.btnQuit = btnQuit;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getLblHighEndNumber() {
        return lblHighEndNumber;
    }

    public void setLblHighEndNumber(JLabel lblHighEndNumber) {
        this.lblHighEndNumber = lblHighEndNumber;
    }

    public JLabel getLblLowEndNumber() {
        return lblLowEndNumber;
    }

    public void setLblLowEndNumber(JLabel lblLowEndNumber) {
        this.lblLowEndNumber = lblLowEndNumber;
    }

    public JLabel getLblTo() {
        return lblTo;
    }

    public void setLblTo(JLabel lblTo) {
        this.lblTo = lblTo;
    }

    public JTextField getTxtNumberGuess() {
        return txtNumberGuess;
    }

    public void setTxtNumberGuess(JTextField txtNumberGuess) {
        this.txtNumberGuess = txtNumberGuess;
    }

    


}
